config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :homes, only: [:index, :show]
  resources :songs, only: [:index, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ApplicationRecord
  validates :title, presence: true
  validates :artist, presence: true
  validates :producer, presence: true
  validates :album, presence: true
  validates :image, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = Song.all
  end

  def show
      @song = Song.find(params[:id])
  end


end

app/views/homes/index.html.erb
<h1>
SeeS Music Official Website
</h1>

<h1><%= link_to 'songs', songs_path %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SeeSMusic</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>
  
    <%= javascript_include_tag "vendor/modernizr" %>
  
  <%= csrf_meta_tags %>
</head>
<body>
  
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">SeeSMusic</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  
  <%- if Rails.env.development? || Rails.env.test? -%> 
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>
  
  <%= yield :extra_footer %>
</body>
</html>

app/views/songs/index.html.erb
<h1> Songs Index Page!! </h1>



<div class="index">
  <ul class="small-block-grid-3">
    <% @songs.each do |song| %>
    <li>
      <h3><%= link_to song.title, song %></h3>
      <img src="<%= song.image %>" width="500px">
      <p><%= song.description %></p>
    </li>
    <% end %>
  </ul>
</div>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>

<div class="index">
  <ul class="small-block-grid-2">
    <li> <img class="songimage" src="<%= @song.image %>"> </li>
    <li>
      <h2><%= @song.title %></h2>
      <p> <strong>Artist:</strong> <%= @song.artist %><p>
      <p> <strong>Producer:</strong> <%= @song.producer %></p>
      <p> <strong>Album:</strong> <%= @song.album %></p>
      <p> <strong>Description:</strong> <%= @song.description %></p>
    </li>

</div>

<p class="embed"> Song: <%= @song.embed.html_safe %></p>